# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@0.0.22
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependecies
          command:  yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command:  yarn run build

      - run:
          name: Run e2e tests
          command:  yarn run test:e2e

workflows:
  build-and-deploy:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          requires:
            - build
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: video-app
          tag: '${CIRCLE_SHA1}'

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: video-app
          cluster-name: video-app
          aws-region: AWS_DEFAULT_REGION
          container-image-name-updates: 'container=video-app,tag=video-app'
