export const SEARCH_VIDEO_REQUEST = 'SEARCH_VIDEO_REQUEST';
export const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
export const SEARCH_VIDEO_FAILURE = 'SEARCH_VIDEO_FAILURE';

export const GET_SAVED_VIDEO_REQUEST = 'GET_SAVED_VIDEO_REQUEST';
export const GET_SAVED_VIDEO_SUCCESS = 'GET_SAVED_VIDEO_SUCCESS';
export const GET_SAVED_VIDEO_FAILURE = 'GET_SAVED_VIDEO_FAILURE';

export const SET_SAVED_VIDEO = 'SET_SAVED_VIDEO';
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE';
export const SET_VIDEO_ID = 'SET_VIDEO_ID';
